import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { CheckCircle2, MessageCircle, Package, Truck, WalletCards } from "lucide-react";
import { demoAddress, demoPaymentLabel, demoRoute, demoSteps, nextDemoStatus, type DemoMessage, type DemoStatus } from "@/lib/demoFlow";

export default function Demo() {
  const [status, setStatus] = useState<DemoStatus>("draft");
  const [messages, setMessages] = useState<DemoMessage[]>([]);
  const [message, setMessage] = useState("");
  const [addressChecked, setAddressChecked] = useState(false);
  const currentIndex = demoSteps.findIndex(step => step.status === status);
  const currentLabel = demoSteps[currentIndex]?.label ?? "Demo";
  const progress = useMemo(() => Math.round((currentIndex / (demoSteps.length - 1)) * 100), [currentIndex]);
  const canCreate = addressChecked && status === "draft";
  const advance = () => { if (canCreate) setStatus("received"); else { const next = nextDemoStatus(status); if (next) setStatus(next); } };
  const send = (sender: DemoMessage["sender"]) => { const text = message.trim(); if (!text) return; setMessages(previous => [...previous, { sender, text }]); setMessage(""); };

  return <main className="min-h-screen bg-[#f7f8fa] px-4 py-8 text-slate-950 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl space-y-6">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><Badge className="mb-3 bg-orange-100 text-orange-700 hover:bg-orange-100">Güvenli demo modu</Badge><h1 className="text-3xl font-black tracking-tight sm:text-5xl">Müşteri → kurye → teslimat</h1><p className="mt-2 max-w-2xl text-slate-600">Bu senaryo gerçek sipariş veya tahsilat oluşturmaz. Adres, rota, kapıda nakit, kurye durumları, sohbet ve muhasebe görünümünü tek ekranda denetler.</p></div><div className="rounded-2xl bg-white px-4 py-3 text-right shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Demo durumu</p><p className="font-black text-orange-600">{currentLabel}</p></div></div>
    <Card className="rounded-3xl border-0 shadow-sm"><CardContent className="p-5 sm:p-7"><div className="mb-4 flex items-center justify-between text-xs font-bold text-slate-500"><span>Akış ilerlemesi</span><span>%{progress}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-[#e54725] transition-all" style={{ width: `${progress}%` }}/></div><div className="mt-5 grid grid-cols-3 gap-3 sm:grid-cols-6">{demoSteps.map((step, index) => <div key={step.status} className={`text-center text-[11px] font-bold ${index <= currentIndex ? "text-orange-700" : "text-slate-400"}`}><div className={`mx-auto mb-2 grid size-8 place-items-center rounded-full ${index <= currentIndex ? "bg-orange-100 text-orange-600" : "bg-slate-100"}`}>{index < currentIndex ? <CheckCircle2 size={16}/> : index + 1}</div>{step.label}</div>)}</div></CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><Card className="rounded-3xl border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><Package size={20} className="text-orange-600"/> Müşteri siparişi</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-400">Alış adresi</p><p className="mt-1 font-semibold">{demoAddress.pickup}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-400">Teslimat adresi</p><p className="mt-1 font-semibold">{demoAddress.delivery}</p></div><Button variant="outline" className="w-full rounded-xl" onClick={() => setAddressChecked(true)} disabled={addressChecked}>{addressChecked ? "Adres doğrulandı" : "Adresleri doğrula"}</Button><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-orange-50 p-4"><p className="text-xs font-bold text-orange-700">Rota</p><p className="mt-1 text-xl font-black">{demoRoute.distanceKm.toFixed(2)} km</p><p className="text-xs text-slate-500">{demoRoute.durationMinutes} dk</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-bold text-emerald-700">Ödeme</p><p className="mt-1 text-sm font-black">{demoPaymentLabel()}</p></div></div><div className="flex flex-col gap-2 sm:flex-row"><Button className="flex-1 rounded-xl bg-[#e54725]" onClick={advance} disabled={!addressChecked || status !== "draft"}>Örnek siparişi oluştur</Button><Button variant="ghost" className="rounded-xl" onClick={() => { setStatus("draft"); setAddressChecked(false); setMessages([]); }}>Sıfırla</Button></div></CardContent></Card>
    <div className="space-y-6"><Card className="rounded-3xl border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><Truck size={20} className="text-orange-600"/> Kurye operasyonu</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-2xl border border-slate-100 p-4"><p className="text-sm font-bold">Demo kurye: Mehmet Yılmaz</p><p className="mt-1 text-sm text-slate-500">Atanan iş: Bostancı → Abbasağa</p></div><Button className="w-full rounded-xl" onClick={advance} disabled={status === "draft" || status === "delivered"}>{status === "received" ? "Siparişi kabul et" : status === "accepted" ? "Ürünü aldım" : status === "picked_up" ? "Yola çıktım" : status === "on_the_way" ? "Teslim edildi" : status === "delivered" ? "Teslim tamamlandı" : "Kurye adımını ilerlet"}</Button><div className="flex items-center gap-2 text-sm font-semibold text-slate-600"><span className={`size-2 rounded-full ${status === "delivered" ? "bg-emerald-500" : "bg-orange-500"}`}/>{currentLabel}</div></CardContent></Card>
      <Card className="rounded-3xl border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><MessageCircle size={20} className="text-orange-600"/> Müşteri–kurye sohbeti</CardTitle></CardHeader><CardContent className="space-y-3"><div className="min-h-28 space-y-2 rounded-2xl bg-slate-50 p-3">{messages.length === 0 ? <p className="text-sm text-slate-400">Demo mesajı göndererek iki yönlü sohbeti deneyin.</p> : messages.map((item, index) => <div key={`${item.sender}-${index}`} className={`max-w-[85%] rounded-xl px-3 py-2 text-sm ${item.sender === "customer" ? "bg-orange-100" : "ml-auto bg-slate-200 text-right"}`}><span className="block text-[10px] font-bold uppercase text-slate-500">{item.sender === "customer" ? "Müşteri" : "Kurye"}</span>{item.text}</div>)}</div><div className="flex gap-2"><Input value={message} onChange={event => setMessage(event.target.value)} placeholder="Örn. Kapıdayım, teslim alabilirsiniz" onKeyDown={event => { if (event.key === "Enter") send("customer"); }}/><Button variant="outline" onClick={() => send("customer")}>Müşteri</Button><Button onClick={() => send("courier")}>Kurye</Button></div></CardContent></Card></div></div>
    <Card className="rounded-3xl border-0 bg-slate-900 text-white shadow-sm"><CardContent className="grid gap-4 p-5 sm:grid-cols-3 sm:p-7"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Toplam</p><p className="mt-1 text-2xl font-black">{demoRoute.totalTl.toLocaleString("tr-TR")} TL</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">İşyeri komisyonu</p><p className="mt-1 text-2xl font-black">{demoRoute.commissionTl.toLocaleString("tr-TR")} TL</p></div><div className="flex items-center gap-2"><WalletCards size={20} className="text-orange-400"/><span className="text-sm text-slate-300">Kapıda nakit tahsilat teslimat sonrası muhasebeleştirilir.</span></div></CardContent></Card>
  </div></main>;
}
